version: '3.9'
services:
  devlake:
    image: apache/devlake:latest
    ports:
      - "4000:4000" # API
      - "8080:8080" # UI
    depends_on:
      - mysql
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_PORT=3306
      - MYSQL_USER=root
      - MYSQL_PASSWORD=admin
      - MYSQL_DB=lake
    volumes:
      - devlake_data:/app/data
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: lake
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
      - ./branding/grafana/custom.ini:/etc/grafana/grafana.ini
      - ./branding/grafana/provisioning:/etc/grafana/provisioning
    environment:
      - GF_INSTALL_PLUGINS=grafana-piechart-panel
    depends_on:
      - devlake
volumes:
  mysql_data:
  grafana_data:
  devlake_data:
